version: "3.9"
   
services:

  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - db-data:/var/lib/mongo/data
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - "27017"
    networks:
      - survey-db

  surveyapi:
    build:
      context: .
    restart: always
    volumes:
      - api-data:/code
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - survey-api
      - survey-db

volumes:
  db-data:
  api-data: 

networks:
  survey-api:
    driver: bridge
  survey-db: