name: Deploy API Code

on:
  push:
    branches:
    - main

jobs:
  Test-And-Deploy:
    name: Test and Deploy
    runs-on: ubuntu-latest

    steps:

    # Checkout from git master branch
    - name: Checkout
      uses: actions/checkout@master
    
    # Python Build Validation for the DAGs 
    - id: run-dags-with-python
      name: Python Tests
      run: |
        pip3 install -r requirements.txt
        python3 surveyapi/manage.py test    
      env:
        DB_USERNAME:  ${{ secrets.DB_USERNAME }}
        DB_PASSWORD:  ${{ secrets.DB_PASSWORD }}
        DB_NAME:  ${{ secrets.DB_NAME }}

    # Run the test on the GCS folder that has the DAGs
    - id: deploy-code
      name: Deploy Code
      run: |
        docker-compose up --build -d