name: Test API Code

on:
  pull_request:
    branches:
    - main

jobs:
  Unit-Test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:

    # Checkout from git master branch
    - name: Checkout
      uses: actions/checkout@master
    
    # Tests
    - id: Test-code
      name: Python Tests
      run: |
        pip3 install -r requirements.txt
        python3 surveyapi/manage.py test    
      env:
        DB_USERNAME:  ${{ secrets.DB_USERNAME }}
        DB_PASSWORD:  ${{ secrets.DB_PASSWORD }}
        DB_NAME:  ${{ secrets.DB_NAME }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DB_CLIENT_HOST: ${{ secrets.DB_CLIENT_HOST }}